// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesWeb.Data;

namespace SalesWeb.Migrations
{
    [DbContext(typeof(SalesWebContext))]
    [Migration("20210216135210_DepartmentsForeignId")]
    partial class DepartmentsForeignId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SalesWeb.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("SalesWeb.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Status");

                    b.Property<int?>("sellerId");

                    b.HasKey("Id");

                    b.HasIndex("sellerId");

                    b.ToTable("SalesRecord");
                });

            modelBuilder.Entity("SalesWeb.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DepartmentId");

                    b.Property<string>("Name");

                    b.Property<double>("baseSalary");

                    b.Property<DateTime>("birthDate");

                    b.Property<string>("email");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("SalesWeb.Models.SalesRecord", b =>
                {
                    b.HasOne("SalesWeb.Models.Seller", "seller")
                        .WithMany("Sales")
                        .HasForeignKey("sellerId");
                });

            modelBuilder.Entity("SalesWeb.Models.Seller", b =>
                {
                    b.HasOne("SalesWeb.Models.Department", "department")
                        .WithMany("Sellers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
